# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="/home/fus/Documents/RISCVTutorial"
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda config --set env_prompt '({name}) '
conda activate /home/fus/Documents/RISCVTutorial/.conda-env
source /home/fus/Documents/RISCVTutorial/scripts/fix-open-files.sh

# Custom alias
export riscv_dir="$(pwd)" 
alias riscv="cd ${riscv_dir}"
alias riscv_fpga="cd ${riscv_dir}/fpga"
alias riscv_generators="cd ${riscv_dir}/sims"
alias riscv_generators="cd ${riscv_dir}/generators"
alias riscv_fpga_sw="cd ${riscv_dir}/fpga/sw"
alias riscv_fpga_src="cd ${riscv_dir}/fpga/src"
alias riscv_fpga_shells="cd ${riscv_dir}/fpga/fpga-shells"
alias riscv_scala_config="cd ${riscv_dir}/generators/chipyard/src/main/scala/config"
alias riscv_device_tree="cd ${riscv_dir}/sims/verilator/generated-src/"
alias Log2CmdExec="tee ${riscv_dir}/CmdExec.log"